### ISSUE TITLE
Bug: Request loop

### ISSUE THREAD

**Issue by birkaany** [davidinoa/pomodoro-app#1]
After I push "start" button first time, notification sounds(mp3 files) requested over and over as the counter is working.

![Screenshot 2023-12-17 at 02 23 21](https://github.com/davidinoa/pomodoro-app/assets/59147411/846fe8f5-1eab-4071-96af-24b6c93c5ab9)

**Comment by davidinoa** [comment]
@birkaany Thank you for reporting the issue!
I resolved it with this commit: [7f883e6](https://github.com/davidinoa/pomodoro-app/commit/7f883e63d3ceb5c98140fb12aaa3e249959a06c7)
